title: remino.github.io
description: Rémino Rem on GitHub

baseurl: /
domain: remino.github.io
url: https://remino.github.io

defaults:
  - scope:
      type: pages
    values:
      layout: default

exclude:
  - README.md
  - LICENSE.txt
  - jeksite
