title: remino@github
description: Rémino Rem on GitHub

domain: remino.github.io
url: https://remino.github.io

defaults:
  - scope:
      type: pages
    values:
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - jeksite
  - repos2json
